name: "cboomer"

packages:
  - build-essential
  - libx11-dev
  - libxrandr-dev
  - libxext-dev
  - libgl-dev
  - cppcheck
  - ninja-build
  - perl
  - python3

env:
  CC: gcc
  CFLAGS: "-Wall -Wextra -pedantic -std=c11 -O2 -g"

setup:
  - make -C $(pwd)
  - echo "\033[32mSetup Complete!\033[0m"

teardown:
  - make -C $(pwd) clean
  - echo "\033[32mTeardown Complete!\033[0m"
