#!/usr/bin/env perl
# cboomer build.ninja generator
# Usage: perl scripts/experimental/generate.pl [--dev] [--live] [--mitshm] [--select]

use strict;
use warnings;
use Getopt::Long qw(:config no_ignore_case);

my ($dev, $live, $mitshm, $select, $help);
GetOptions(
    'dev'    => \$dev,
    'live'   => \$live,
    'mitshm' => \$mitshm,
    'select' => \$select,
    'help'   => \$help,
) or die "Usage: $0 [--dev] [--live] [--mitshm] [--select]\n";

if ($help) {
    print <<'USAGE';
Usage: generate.pl [OPTIONS]
Generate build.ninja for cboomer.

Options:
  --dev      Enable DEVELOPER mode (shader hot-reload)
  --live     Enable LIVE mode (continuous screenshot refresh)
  --mitshm   Enable MIT-SHM extension
  --select   Enable window selection at startup
  --help     Show this message
USAGE
    exit 0;
}

my @defines;
push @defines, '-DDEVELOPER' if $dev;
push @defines, '-DLIVE'      if $live;
push @defines, '-DMITSHM'    if $mitshm;
push @defines, '-DSELECT'    if $select;

my $git_hash = `git rev-parse HEAD 2>/dev/null || echo unknown`;
chomp $git_hash;

my $git_cflags = qq{-DGIT_HASH=\\"$git_hash\\"};
my $feature_cflags = @defines ? ' ' . join(' ', @defines) : '';
my $all_cflags = "-Wall -Wextra -pedantic -std=c11 -O2 -g -Ibuild $git_cflags$feature_cflags";

my $outfile = 'build.ninja';
open my $fh, '>', $outfile or die "Cannot write $outfile: $!\n";

print $fh <<'NINJA' or die "Write error: $!\n";
ninja_required_version = 1.3

# Generated by scripts/experimental/generate.pl
# NOTE: DO NOT EDIT BY HAND
cc = gcc
NINJA

print $fh "cflags = $all_cflags\n";

print $fh <<'NINJA';
ldlibs = -lX11 -lXrandr -lXext -lGL -lm -lz

rule mkdir
  command = mkdir -p $out
  description = MKDIR $out

rule gen_shaders
  command = scripts/gen_shaders.sh $out
  description = GEN shaders.h

rule cc
  depfile = $out.d
  command = $cc $cflags -MMD -MF $out.d -c -o $out $in
  description = CC $in

rule link
  command = $cc $cflags -o $out $in $ldlibs
  description = LINK $out

build build: mkdir

FRAG_SHADER_NAMES = frag_invert frag_crt frag_grayscale frag_edge frag_vhsglitch frag_distortion frag_zoomblur frag_posterize frag_pixelate frag_sepia frag_emboss
NINJA

print $fh "\n";

my @frag_names = qw(frag_invert frag_crt frag_grayscale frag_edge frag_vhsglitch frag_distortion frag_zoomblur frag_posterize frag_pixelate frag_sepia frag_emboss);
my $shader_inputs = join(' ',
    'src/shaders/vert.glsl',
    'src/shaders/frag.glsl',
    (map { "src/shaders/$_.glsl" } @frag_names),
    'src/shaders/osd_vert.glsl',
    'src/shaders/osd_frag.glsl',
);
print $fh "build build/shaders.h: gen_shaders $shader_inputs || build\n";
print $fh "\n";

my @sources = qw(main la config navigation screenshot osd);
for my $src (@sources) {
    my $order_only = ($src eq 'main' || $src eq 'osd')
        ? ' || build/shaders.h'
        : '';
    print $fh "build build/$src.o: cc src/$src.c$order_only\n";
}
print $fh "\n";

my $objs = join(' ', map { "build/$_.o" } @sources);
print $fh "build cboomer: link $objs\n";
print $fh "\n";

print $fh "default cboomer\n";

close $fh or die "Close error: $!\n";

print "Generated $outfile\n";
print "Features:" . (@defines ? " @defines" : " (none)") . "\n";
