#!/usr/bin/env python3
# cboomer build.ninja generator
# Usage: python scripts/experimental/generate.py [--dev] [--live] [--mitshm] [--select]
import argparse
import subprocess

FRAG_NAMES = [
    'frag_NEW_SHADER',
    'frag_invert', 'frag_crt', 'frag_grayscale', 'frag_edge',
    'frag_vhsglitch', 'frag_distortion', 'frag_zoomblur',
    'frag_posterize', 'frag_pixelate', 'frag_sepia', 'frag_emboss',
]

SOURCES = ['main', 'la', 'config', 'navigation', 'screenshot', 'osd']

def main():
    parser = argparse.ArgumentParser(description='Generate build.ninja for cboomer')
    parser.add_argument('--dev', action='store_true', help='Enable DEVELOPER mode (shader hot-reload)')
    parser.add_argument('--live', action='store_true', help='Enable LIVE mode (continuous screenshot refresh)')
    parser.add_argument('--mitshm', action='store_true', help='Enable MIT-SHM extension')
    parser.add_argument('--select', action='store_true', help='Enable window selection at startup')
    args = parser.parse_args()

    defines = []
    if args.dev:    defines.append('-DDEVELOPER')
    if args.live:   defines.append('-DLIVE')
    if args.mitshm: defines.append('-DMITSHM')
    if args.select: defines.append('-DSELECT')

    try:
        git_hash = subprocess.run(
            ['git', 'rev-parse', 'HEAD'],
            capture_output=True, text=True, timeout=5,
        ).stdout.strip()
    except Exception:
        git_hash = 'unknown'

    git_cflags = f'-DGIT_HASH=\\"{git_hash}\\"'
    cflags = ' '.join(['-Wall', '-Wextra', '-pedantic', '-std=c11', '-O2', '-g', '-Ibuild', git_cflags] + defines)

    outfile = 'build.ninja'

    with open(outfile, 'w') as f:
        f.write('ninja_required_version = 1.3\n')
        f.write('\n')
        f.write('# Generated by scripts/experimental/generate.py\n')
        f.write('# NOTE: DO NOT EDIT BY HAND\n')
        f.write('cc = gcc\n')
        f.write(f'cflags = {cflags}\n')
        f.write('ldlibs = -lX11 -lXrandr -lXext -lGL -lm -lz\n')
        f.write('\n')

        f.write('rule mkdir\n')
        f.write('  command = mkdir -p $out\n')
        f.write('  description = MKDIR $out\n')
        f.write('\n')

        f.write('rule gen_shaders\n')
        f.write('  command = scripts/gen_shaders.sh $out\n')
        f.write('  description = GEN shaders.h\n')
        f.write('\n')

        f.write('rule cc\n')
        f.write('  depfile = $out.d\n')
        f.write('  command = $cc $cflags -MMD -MF $out.d -c -o $out $in\n')
        f.write('  description = CC $in\n')
        f.write('\n')

        f.write('rule link\n')
        f.write('  command = $cc $cflags -o $out $in $ldlibs\n')
        f.write('  description = LINK $out\n')
        f.write('\n')

        f.write('build build: mkdir\n')
        f.write('\n')

        f.write('FRAG_SHADER_NAMES = ' + ' '.join(FRAG_NAMES) + '\n')
        f.write('\n')

        shader_inputs = ' '.join(
            ['src/shaders/vert.glsl', 'src/shaders/frag.glsl']
            + [f'src/shaders/{n}.glsl' for n in FRAG_NAMES]
            + ['src/shaders/osd_vert.glsl', 'src/shaders/osd_frag.glsl']
        )
        f.write(f'build build/shaders.h: gen_shaders {shader_inputs} || build\n')
        f.write('\n')

        for src in SOURCES:
            order_only = ' || build/shaders.h' if src in ('main', 'osd') else ''
            f.write(f'build build/{src}.o: cc src/{src}.c{order_only}\n')
        f.write('\n')

        objs = ' '.join(f'build/{s}.o' for s in SOURCES)
        f.write(f'build cboomer: link {objs}\n')
        f.write('\n')

        f.write('default cboomer\n')

    print(f'Generated {outfile}')
    print(f"Features: {' '.join(defines) if defines else '(none)'}")


if __name__ == '__main__':
    main()
